export const REQUEST_FETCH_PRODUCT = "REQUEST_FETCH_PRODUCT";
export const RECEIVE_FETCH_PRODUCT = "RECEIVE_FETCH_PRODUCT";

export const REQUEST_SORT_PRODUCT = "REQUEST_SORT_PRODUCT";
export const RECEIVE_SORT_PRODUCT = "RECEIVE_SORT_PRODUCT";

export const REQUEST_SIZE_PRODUCT = "REQUEST_SIZE_PRODUCT";
export const RECEIVE_SIZE_PRODUCT = "RECEIVE_SIZE_PRODUCT";

export const REQUEST_ADD_TO_CART = "REQUEST_ADD_TO_CART";
export const RECEIVE_ADD_TO_CART = "RECEIVE_ADD_TO_CART";

export const REQUEST_DELETE_CART_ITEM = "REQUEST_DELETE_CART_ITEM";
export const RECEIVE_DELETE_CART_ITEM = "RECEIVE_DELETE_CART_ITEM";
